---
abstract: 'An extension for DB::CouchDB that does magic stuff'
author:
  - 'Lenz Gschwendtner <norbu09@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DB-CouchDB-Magic
no_index:
  directory:
    - inc
    - t
requires:
  Encoding::FixLatin: 0
  MIME::Base64: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.02
